apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz
  labels:
    app: quiz
    version: ch02
spec:
  selector:
    matchLabels:
      app: quiz
      version: ch02
  template:
    metadata:
      labels:
        app: quiz
        version: ch02
    spec:
      containers:
        - name: web
          image: kiamol/ch02-whoami
